trigger:
- main

pool: asr

jobs:
 - job: terraform_install
   displayName: install
   steps:
     - task: TerraformTask@5
       inputs:
         provider: 'azurerm'
         command: 'init'
         backendAzureRmResourceGroupName: 'for-backend'
         backendAzureRmStorageAccountName: 'pipelinekeliye'
         backendAzureRmContainerName: 'pipestorage'
         backendAzureRmKey: 'rtp.tfstate'