name: terraform_workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: 7732d75f-b6e3-46e8-9b93-44b791e428a8
          tenant-id: 271363dd-c06f-4cf7-9801-1caf3c8e1855
          subscription-id: 05dbb74f-6152-4a1d-a1fd-c49be5c3fd99

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # Save tfplan for next job
      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

      # 🔍 Run tfsec only on PR
      - name: Run tfsec
        if: github.event_name == 'pull_request'
        uses: aquasecurity/tfsec-action@v1.0.3

      # 🔍 Run checkov only on PR
      - name: Run Checkov
        if: github.event_name == 'pull_request'
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

  apply:
    needs: plan
    runs-on: self-hosted

    # 👇 Only run on main branch
    if: github.ref == 'refs/heads/main'

    # 👇 THIS is correct place for environment
    environment:
      name: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: 7732d75f-b6e3-46e8-9b93-44b791e428a8
          tenant-id: 271363dd-c06f-4cf7-9801-1caf3c8e1855
          subscription-id: 05dbb74f-6152-4a1d-a1fd-c49be5c3fd99

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Download tfplan
      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
