
name: dummy_workflow
on:  
  workflow_dispatch:
permissions:
  id-token: write
  contents: read  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: azure login OIDC
        uses: azure/login@v2
        with:
          client-id: 7732d75f-b6e3-46e8-9b93-44b791e428a8
          tenant-id: 271363dd-c06f-4cf7-9801-1caf3c8e1855
          subscription-id: 05dbb74f-6152-4a1d-a1fd-c49be5c3fd99
