
name: dummy_workflow
on:  
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: azure login
        run: az login --service-principal -u 7732d75f-b6e3-46e8-9b93-44b791e428a8 -p yIM8Q~dCYummEo1f6HHSDXVkZUjMR25bA2ZBzc-V --tenant 271363dd-c06f-4cf7-9801-1caf3c8e1855
